#!/usr/bin/env bash
# Builds ui/js/vendor/anthropic-sdk.js — the official @anthropic-ai/sdk bundled as a classic
# browser script (esbuild IIFE, global `AnthropicSDK`, so `new AnthropicSDK.default({...})`).
# The UI has no build step and no CDN, so the bundle is committed. Re-run this after changing
# the pinned versions in tools/sdk-bundle/package.json (then `npm install` there to refresh the lock).
#
#   bash tools/build-sdk-bundle.sh
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIR="$HERE/sdk-bundle"
OUT_REL="../../ui/js/vendor/anthropic-sdk.js"
OUT="$DIR/$OUT_REL"

cd "$DIR"
npm ci --no-audit --no-fund

SDK_VERSION="$(node -p "require('./node_modules/@anthropic-ai/sdk/package.json').version")"
ESBUILD_VERSION="$(node -p "require('./node_modules/esbuild/package.json').version")"

mkdir -p "$(dirname "$OUT")"
npx --no-install esbuild entry.js \
  --bundle \
  --format=iife \
  --global-name=AnthropicSDK \
  --platform=browser \
  --minify \
  --target=es2020 \
  --legal-comments=eof \
  --outfile="$OUT_REL"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
{
  printf '/* @anthropic-ai/sdk %s (esbuild %s) — generated by tools/build-sdk-bundle.sh — do not edit */\n' \
    "$SDK_VERSION" "$ESBUILD_VERSION"
  cat "$OUT"
  # The SDK sources carry no /*! legal comments, so append its MIT notice (required when redistributing).
  printf '\n/*! @anthropic-ai/sdk %s — license:\n' "$SDK_VERSION"
  sed 's#\*/#* /#g' node_modules/@anthropic-ai/sdk/LICENSE
  printf '*/\n'
} > "$TMP"
cat "$TMP" > "$OUT"   # keep the output file's normal permissions (mktemp files are 0600)
rm -f "$TMP"
trap - EXIT

echo "Wrote $(cd "$(dirname "$OUT")" && pwd)/$(basename "$OUT") ($(wc -c < "$OUT") bytes, @anthropic-ai/sdk $SDK_VERSION)"
